name: green_cycle_fyp
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  #Provider
  provider: ^6.1.5

  #Icons
  font_awesome_flutter: ^10.8.0
  cupertino_icons: ^1.0.8

  #Form
  flutter_form_builder: ^10.0.1
  form_builder_validators: ^11.1.2

  #Formatting
  intl_phone_field: ^3.2.0
  intl: ^0.20.2

  #Navigation
  auto_route: ^9.3.0+1
  
  #Image
  image_picker: ^1.1.2
  cached_network_image: ^3.4.0
  flutter_blurhash: ^0.9.1
  multi_image_picker_view: ^3.0.0
  carousel_slider: ^5.1.1

  #Map Launcher
  map_launcher: ^3.5.0

  #URL Launcher
  url_launcher: ^6.3.2

  #Loading Indicator
  flutter_easyloading: ^3.0.5
  flutter_spinkit: ^5.2.1
  adaptive_widgets_flutter: ^0.1.5

  #Skeleton Loader
  skeletonizer: ^2.1.0

  #Splash Screen
  flutter_native_splash: ^2.4.6

  #Flutter App Icon
  flutter_launcher_icons: ^0.14.4

  #Google Map
  google_maps_flutter: ^2.12.3
  google_places_flutter: ^2.1.0
  geolocator: ^14.0.2

  #Data
  dio: ^5.7.0
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  shared_preferences: ^2.5.3

  #Firebase
  firebase_core: ^3.10.1
  firebase_auth: ^5.4.1
  firebase_storage: ^12.4.1

  #Snackbar
  fluttertoast: ^8.2.12


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.14
  auto_route_generator: ^9.3.1
  freezed: ^2.5.8
  json_serializable: ^6.9.0


# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/images/
  #   - images/a_dot_ham.jpeg


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
