// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBQ_RgCbPChpmKsc6fkv22v37_Y18MpyI',
    appId: '1:931591092978:web:a1fd3462aea8548686ae6b',
    messagingSenderId: '931591092978',
    projectId: 'greencyclefyp',
    authDomain: 'greencyclefyp.firebaseapp.com',
    storageBucket: 'greencyclefyp.firebasestorage.app',
    measurementId: 'G-TRZMBXHKR8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRTVEeYdtQ6ceOi34dcl_mqxGhdF7i_M8',
    appId: '1:931591092978:android:48af08463f2122bf86ae6b',
    messagingSenderId: '931591092978',
    projectId: 'greencyclefyp',
    storageBucket: 'greencyclefyp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxciEG34Z5rkCDcRhWS-_ImO9gP1mNPjs',
    appId: '1:931591092978:ios:10fb72fb22ab6c7c86ae6b',
    messagingSenderId: '931591092978',
    projectId: 'greencyclefyp',
    storageBucket: 'greencyclefyp.firebasestorage.app',
    iosBundleId: 'com.example.greenCycleFyp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxciEG34Z5rkCDcRhWS-_ImO9gP1mNPjs',
    appId: '1:931591092978:ios:10fb72fb22ab6c7c86ae6b',
    messagingSenderId: '931591092978',
    projectId: 'greencyclefyp',
    storageBucket: 'greencyclefyp.firebasestorage.app',
    iosBundleId: 'com.example.greenCycleFyp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBQ_RgCbPChpmKsc6fkv22v37_Y18MpyI',
    appId: '1:931591092978:web:351f8ea90110cb2886ae6b',
    messagingSenderId: '931591092978',
    projectId: 'greencyclefyp',
    authDomain: 'greencyclefyp.firebaseapp.com',
    storageBucket: 'greencyclefyp.firebasestorage.app',
    measurementId: 'G-EX7LSQ6YCG',
  );
}
